# Configuración general
selected_model: "pinn_v1"  # Nombre del modelo a utilizar (debe estar en la sección 'models')
selected_loss: "mse"       # Nombre de la función de pérdida (debe estar en la sección 'loss_functions')

# Definiciones de modelos disponibles
# Nota: Las dimensiones de entrada y salida (primera y última capa) son determinadas automáticamente
# basadas en el tipo de problema físico. No es necesario incluirlas en la definición de capas.
models:
  # For standard models - input/output dimensions set by physics_type
  pinn_v1:
    type: "mlp"                      
    layers: [50, 50, 50, 50]   # Hidden layers only - input/output are set by physics_type
    activation_function: "Tanh"
    learning_rate: 0.001
    physics_type: "burgers"  # Determines input (2) and output (1) dimensions
    
  pinn_v2:
    type: "mlp_residual"
    layers: [64, 64, 64, 64]
    activation_function: "Swish"
    learning_rate: 0.0005
    physics_type: "burgers"  # Determines input (2) and output (1) dimensions
    
  pinn_small:
    type: "mlp"
    layers: [20, 20]
    activation_function: "ReLU"
    learning_rate: 0.002
    physics_type: "burgers"  # Determines input (2) and output (1) dimensions

  # For fluid models - input/output dimensions set by physics_type
  navier_stokes:
    type: "navier_stokes"
    layers: [64, 64, 64, 64]   # Hidden layers only
    activation_function: "Tanh"
    learning_rate: 0.0005
    physics_type: "navier_stokes"  # Determines input (3) and output (3) dimensions
    
  kovasznay:
    type: "kovasznay"
    layers: [40, 40, 40]       # Hidden layers only
    activation_function: "Tanh"
    learning_rate: 0.001
    re: 40.0
    physics_type: "kovasznay"  # Determines input (2) and output (3) dimensions
    
  taylor_green:
    type: "taylor_green"
    layers: [64, 64, 64, 64]   # Hidden layers only
    activation_function: "Swish"
    learning_rate: 0.0008
    nu: 0.01
    physics_type: "taylor_green"  # Determines input (3) and output (3) dimensions
    
  cavity_flow:
    type: "cavity_flow"
    layers: [50, 50, 50, 50]   # Hidden layers only
    activation_function: "Tanh"
    learning_rate: 0.001
    physics_type: "cavity_flow"  # Determines input (2) and output (3) dimensions

# Definiciones de funciones de pérdida
loss_functions:
  mse:
    type: "mean_squared_error"
    weight: 1.0
    
  physics_informed:
    type: "physics_informed_loss"
    data_weight: 1.0
    physics_weight: 0.5
    
  weighted_mse:
    type: "weighted_mse"
    interior_weight: 1.0
    boundary_weight: 10.0

training:
  epochs: 1
  batch_size: 64
  optimizer: "Adam"
  optimizer_params:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0
  scheduler: "ReduceLROnPlateau"
  scheduler_params:
    factor: 0.5
    patience: 10
    threshold: 1e-4
    min_lr: 1e-6
  early_stopping:
    enabled: true
  epochs_no_improve: 20
  min_loss_improvement: 1e-4
  seed: 42
  memory_limit_gb: 4

physics:
  nu: 0.01
  boundary_type: "dirichlet"
  physics_type: "burgers"  # Tipo de física: "burgers", "kovasznay", "taylor_green", "cavity_flow"

logging:
  level: "INFO"
  output_folder: "output"

# Data configuration
data_generation:
  type: "burgers"  # Opciones: burgers, kovasznay, taylor_green, lid_driven_cavity
  spatial_points: 256
  time_points: 100
  # Parámetros específicos para cada tipo de datos
  Re: 40             # Para Kovasznay
  U0: 1.0            # Para Taylor-Green y cavidad
  resolution: 32     # Para Kovasznay y cavidad (N)
  Nx: 32             # Para Taylor-Green
  Ny: 32             # Para Taylor-Green
  T: 2.0             # Para Taylor-Green y cavidad
  num_steps: 50      # Para Taylor-Green y cavidad

evaluation:
  model_path: "output/Model_mlp_1_0.001_42/model/weights_model.pth"  # Ruta al modelo entrenado
  data_path: "data/training/burgers_shock_mu_01_pi.mat"  # Datos para evaluar
  data_dir: "data/training"  # Directorio donde buscar datos
  output_folder: "evaluation_results"  # Carpeta donde guardar resultados
  metrics: ["MAE", "MSE", "RMSE", "R2"]  # Métricas a calcular
  visualize: true  # Generar visualizaciones
  compare_with_analytical: false  # Comparar con solución analítica
